# Version of the configuration file
version: 1.0
# Input files and directories
input:
  samples: "/home/user/MARTA/LABO/PULPO/PULPO_synthetic/config/samples.tsv"
  bionanodata: "/home/user/MARTA/LABO/PULPO/PULPO_synthetic/DATA/"
directories:
 # workdirectory: "/home/user/MARTA/LABO/PULPO/PULPO_synthetic"
  workdirectory: "/home/user/MARTA/LABO/PULPO/PULPO_synthetic/CNVprueba"
  pythonenvdir: "/home/user/miniconda3/envs/PULPO/bin/python3.10"
  scriptsdir: "/home/user/MARTA/LABO/PULPO/PULPO_synthetic/scripts"
# Specific configuration of the analysis
# Type of analysis: simple sample or cohort
analysis:
  analysis_type: "SVs"  # options: SVs, CNVs, SVs_and_CNVs
  run_cohort_analysis: TRUE # TRUE - Cohort analysis | FALSE - Only individual analysis
  zip: FALSE # TRUE - Samples are compressed | FALSE - Files are descompressed
file_types:
  CNVs: "txt" # it can be "bed" "txt" or "csv"
  SVs: "smap" # it can be "bedpe" or "smap"
BionanoAccess:
  version: "1.6.1" #options: 1.6.1 or 1.8.1
  

